name: scikit-query
channels:
  - anaconda-fusion
  - defaults
dependencies:
  pip:
    - scikit-learn==1.2.2
    - numpy==1.24.3
    - pandas==2.0.1
    - scipy==1.10.1
    - cvxopt==1.3.1
    - scikit-fuzzy==0.4.2
    - plotly==5.14.1
    - matplotlib==3.7.1
    - active-semi-supervised-clustering
