name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
          - "3.13"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install conda=25.1.1
        conda install python==${{ matrix.python-version }}
        pip install polars pandas numpy scipy scikit-learn scikit-learn-intelex scikit-fuzzy clustering-benchmarks active-semi-supervised-clustering cvxopt
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        git clone https://github.com/gagolews/clustering-data-v1.git
        conda install pytest pytest-cov
        pytest --cov-report xml --cov-config=.coveragerc --cov=skquery
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: CODECOV_TOKEN:${{ secrets.CODECOV_TOKEN }}
