# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: [push]


permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Insert Version number
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        sed -i -E "s/__version__ = .*/__version__ = \"$RELEASE_VERSION\"/" skquery/__init__.py
        cat skquery/__init__.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        python .github/workflows/update_requirements.py
        pip install twine
        pip install wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
